namespace ScreenshotStudio.GameData.Excel;

using Anamnesis.Utils;
using Dalamud.Game.ClientState.Objects.Enums;
using Lumina.Data;
using Lumina.Excel;
using ScreenshotStudio.GameData.Sheets;
using ScreenshotStudio.Structs;
using System.Text;
using ScreenshotStudio.Structs.Extensions;

[Sheet("ENpcBase", 0x464052cd)]
public class EventNpc : LibraryExcelRow
{
	public string? AppearanceHash { get; private set; }

	// A special property generated by EventNpcSheet showing the row that this
	// event NPC is a duplicate of.
	// Null if this is not a duplicate.
	public uint? DuplicateRow { get; set; } = null;

	// Customize
	public float Scale { get; protected set; } = 1.0f;
	public ModelChara? ModelChara { get; protected set; }

	public Customize Customize { get; protected set; }
	public NpcEquipment Equipment { get; protected set; } = new();
	public NpcEquip? NpcEquip { get; protected set; }

	public override void PopulateData(RowParser parser, Lumina.GameData gameData, Language language)
	{
		base.PopulateData(parser, gameData, language);

		// Customize
		this.Scale = parser.ReadColumn<float>(34);
		this.ModelChara = parser.ReadRowReference<ushort, ModelChara>(35);

		Customize c;

		for(int i = 0; i < Customize.NumOptions; i++)
		{
			CustomizeIndex index = (CustomizeIndex)i;
			int row = 36 + i;
			byte val = parser.ReadColumn<byte>(row);

			c.SetValue(index, val);
		}

		this.Customize = c;

		this.Equipment.Parse(parser, 65);

		this.NpcEquip = parser.ReadRowReference<ushort, NpcEquip>(63);
		/*if (npcEquip?.RowId == 175 || npcEquip?.RowId == 0)
		{
			this.Equipment = npcEquip.Equipment;
		}*/

		this.Tags.Add(this.Customize.Race?.ToTags());
		this.Tags.Add(this.Customize.Tribe?.ToTags());
		this.Tags.Add(this.Customize.Gender.ToTags());

		this.GenerateAppearanceHash();
	}

	public unsafe void Apply(Actor* actor)
	{
		actor->UpdateCustomize(this.Customize, Actor.UpdateSource.Library);
		this.Equipment.ApplyToActor(actor, this.NpcEquip?.Equipment);
	}

	protected void GenerateAppearanceHash()
	{
		StringBuilder sb = new();

		// Customize
		this.AddToString(this.Scale, sb);
		this.AddToString(this.ModelChara, sb);

		for (int i = 0; i < Customize.NumOptions; i++)
		{
			this.AddToString(this.Customize.GetValue((CustomizeIndex)i), sb);
		}

		this.Equipment.GetStringForHash(sb);

		this.AppearanceHash = HashUtility.GetHashString(sb.ToString());
	}

	private void AddToString(object? val, StringBuilder builder)
	{
		if (val == null)
		{
			builder.Append("_");
		}
		else if (val is ExcelRow row)
		{
			builder.Append(row.RowId);
		}
		else
		{
			builder.Append(val);
		}
	}
}