namespace ScreenshotStudio.GameData.Excel;

using Dalamud.Game.ClientState.Objects.Enums;
using FFXIVClientStructs.FFXIV.Client.Game.Character;
using Lumina.Excel;
using ScreenshotStudio.Data;
using ScreenshotStudio.Library;
using ScreenshotStudio.Library.Executors;
using ScreenshotStudio.Utils;
using System.Text;
using WpfUtils;

public abstract class NpcBase : LibraryExcelRow, ICharacterAppearance
{
	private CustomizeData customize;

	// A special property generated by EventNpcSheet showing the row that this
	// event NPC is a duplicate of.
	// Null if this is not a duplicate.
	public uint? DuplicateRow { get; set; } = null;
	public string? AppearanceHash { get; private set; }

	public float Scale { get; protected set; } = 1.0f;
	public ModelChara? ModelChara { get; protected set; }

	public ref CustomizeData Customize { get => ref this.customize; }
	public NpcEquipment Equipment { get; protected set; } = new();
	public virtual NpcEquipment? BackupEquipment => null;

	public abstract string Key { get; }

	// don't show duplicates in the library
	public override bool IsValid => base.IsValid && this.DuplicateRow == null;

	public void SetName()
	{
		// lookup name
		string? name = null;
		if (DataService.NpcNames?.TryGetValue(this.Key, out string? npcNameKey) ?? false)
		{
			if (npcNameKey.StartsWith("N:"))
			{
				uint nameId = uint.Parse(npcNameKey.Substring(2));
				BattleNpcName? npcName = GameDataService.GetRow<BattleNpcName>(nameId);
				if (npcName != null)
				{
					name = npcName.Name;
				}
			}
			else
			{
				name = npcNameKey;
			}
		}

		if (name != null)
		{
			this.Tags.Add("Named");
			this.Name = name;
		}
	}

	public void GenerateTags()
	{
		this.Tags.Add("NPC");

		if (this.ModelChara != null)
		{
			if (this.ModelChara.Type == 1)
			{
				this.Tags.Add(this.Customize.GetRace()?.ToTags());
				this.Tags.Add(this.Customize.GetTribe()?.ToTags());
				this.Tags.Add(this.Customize.GetGender().ToTags());
			}

			this.ModelChara.GetTags(this.Tags);
		}
	}

	public unsafe void Apply(Character* character)
	{
		bool redraw = false;
		if (this.ModelChara != null)
		{
			redraw = true;
			character->UpdateModel(this.ModelChara, CharacterExtensions.UpdateSource.Library, false);
		}

		character->UpdateCustomize(this.Customize, redraw, CharacterExtensions.UpdateSource.Library);
		this.Equipment.ApplyTo(character, this.BackupEquipment);
	}

	public override bool Search(string[]? query)
	{
		bool result = base.Search(query);

		if (this.DuplicateRow != null)
			result |= SearchUtility.Matches(this.DuplicateRow, query);

		if (this.ModelChara != null)
			result |= SearchUtility.Matches(this.ModelChara.RowId, query);

		return result;
	}

	public override EntryExecutor? GetExecutor()
	{
		return new AppearanceExecutor(this, this);
	}

	protected void GenerateAppearanceHash()
	{
		StringBuilder sb = new();

		// Customize
		this.AddToString(this.Scale, sb);
		this.AddToString(this.ModelChara, sb);

		for (int i = 0; i < CustomizeDataExtensions.NumOptions; i++)
		{
			this.AddToString(this.Customize.GetValue((CustomizeIndex)i), sb);
		}

		this.Equipment.GetStringForHash(sb);

		this.AppearanceHash = HashUtility.GetHashString(sb.ToString());
	}

	private void AddToString(object? val, StringBuilder builder)
	{
		if (val == null)
		{
			builder.Append("_");
		}
		else if (val is ExcelRow row)
		{
			builder.Append(row.RowId);
		}
		else
		{
			builder.Append(val);
		}
	}
}
