namespace ScreenshotStudio.GameData.Excel;

using Anamnesis.Utils;
using Dalamud.Game.ClientState.Objects.Enums;
using Lumina.Excel;
using ScreenshotStudio.Structs;
using System.Text;
using ScreenshotStudio.Library;
using ScreenshotStudio.Data;
using WpfUtils;

public abstract class NpcBase : LibraryExcelRow, IActorAppearance
{
	// A special property generated by EventNpcSheet showing the row that this
	// event NPC is a duplicate of.
	// Null if this is not a duplicate.
	public uint? DuplicateRow { get; set; } = null;
	public string? AppearanceHash { get; private set; }

	public float Scale { get; protected set; } = 1.0f;
	public ModelChara? ModelChara { get; protected set; }

	public Customize Customize { get; protected set; }
	public NpcEquipment Equipment { get; protected set; } = new();
	public virtual NpcEquipment? BackupEquipment => null;

	public abstract string Key { get; }

	// don't show duplicates in the library
	public override bool IsValid => base.IsValid && this.DuplicateRow == null;

	public void SetName()
	{
		// lookup name
		string? name = null;
		if (DataService.NpcNames?.TryGetValue(this.Key, out string? npcNameKey) ?? false)
		{
			if (npcNameKey.StartsWith("N:"))
			{
				uint nameId = uint.Parse(npcNameKey.Substring(2));
				BattleNpcName? npcName = GameDataService.GetRow<BattleNpcName>(nameId);
				if (npcName != null)
				{
					name = npcName.Name;
				}
			}
			else
			{
				name = npcNameKey;
			}
		}

		////this.Name = $"{this.NpcType} NPC #{this.RowId}";

		if (name != null)
		{
			this.Tags.Add("Named");
			this.Name = name;
		}
		else
		{
			this.Tags.Add("Unnamed");
		}
	}

	public void GenerateTags()
	{
		this.Tags.Add("NPC");

		if (this.ModelChara != null)
		{
			if (this.ModelChara.Type == 1)
			{
				this.Tags.Add(this.Customize.Race?.ToTags());
				this.Tags.Add(this.Customize.Tribe?.ToTags());
				this.Tags.Add(this.Customize.Gender.ToTags());
			}

			this.ModelChara.GetTags(this.Tags);
		}
	}

	public unsafe void Apply(Actor* actor)
	{
		bool redraw = false;
		if (this.ModelChara != null)
		{
			redraw = true;
			actor->UpdateModel(this.ModelChara, Actor.UpdateSource.Library, false);
		}

		actor->UpdateCustomize(this.Customize, Actor.UpdateSource.Library, redraw);
		this.Equipment.ApplyToActor(actor, this.BackupEquipment);
	}

	public override bool Search(string[]? query)
	{
		bool result = false;
		result |= base.Search(query);

		if (this.DuplicateRow != null)
			result |= SearchUtility.Matches(this.DuplicateRow, query);

		if (this.ModelChara != null)
			result |= SearchUtility.Matches(this.ModelChara.RowId, query);

		return result;
	}

	protected void GenerateAppearanceHash()
	{
		StringBuilder sb = new();

		// Customize
		this.AddToString(this.Scale, sb);
		this.AddToString(this.ModelChara, sb);

		for (int i = 0; i < Customize.NumOptions; i++)
		{
			this.AddToString(this.Customize.GetValue((CustomizeIndex)i), sb);
		}

		this.Equipment.GetStringForHash(sb);

		this.AppearanceHash = HashUtility.GetHashString(sb.ToString());
	}

	private void AddToString(object? val, StringBuilder builder)
	{
		if (val == null)
		{
			builder.Append("_");
		}
		else if (val is ExcelRow row)
		{
			builder.Append(row.RowId);
		}
		else
		{
			builder.Append(val);
		}
	}
}
