<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net8.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<UseWPF>true</UseWPF>
	<Platforms>x64</Platforms>
  </PropertyGroup>

	<PropertyGroup>
		<DalamudLibPath>$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
		<RootNamespace>StudioFourteen.Test</RootNamespace>
	</PropertyGroup>
	<PropertyGroup Condition="'$(CI)' == 'true' OR '$(IsCI)' == 'true'">
		<DalamudLibPath>$(DALAMUD_HOME)/</DalamudLibPath>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Lumina" Version="4.1.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\StudioFourteen\StudioFourteen.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="FFXIVClientStructs">
			<HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>$(DalamudLibPath)Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="Dalamud">
			<HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
		</Reference>
		<Reference Include="ImGui.NET">
			<HintPath>$(DalamudLibPath)ImGui.NET.dll</HintPath>
		</Reference>
		<Reference Include="ImGuiScene">
			<HintPath>$(DalamudLibPath)ImGuiScene.dll</HintPath>
		</Reference>
		<Reference Include="Lumina">
			<HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
		</Reference>
		<Reference Include="Lumina.Excel">
			<HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
