// .                    @@             _____ _______ _    _ _____ _____ ____
//          @       @@@@@             / ____|__   __| |  | |  __ \_   _/ __ \
//         @@@  @@@@                 | (___    | |  | |  | | |  | || || |  | |
//         @@@@@@@@@  @    @          \___ \   | |  | |  | | |  | || || |  | |
//        @@@@       @@@@@@@          ____) |  | |  | |__| | |__| || || |__| |
//    @@@@@             @@@          |_____/   |_|   \____/|_____/_____\____/
//     @@@      @@@      @@        ___     _    _   _  __   _____  ___  ___  _  _
//      @@    @@@@@@@    @@       |  _|  / _ \ | | | || _ \|_   _|| __|| __|| \| |
//      @@    @@@@@@@    @   @    | __| | (_) || |_| ||   /  | |  | _| | _| | .` |
//    @@@@      @@@      @@@@     |_|    \___/  \___/ |_|_\  |_|  |___||___||_|\_|
//     @@@@             @@@        https://github.com/UnlostWorld/StudioFourteen
//       @@@@@      @@@@@
//        @@@@@@@@@@@@@@                This software is licensed under the
//            @@@@  @                  GNU AFFERO GENERAL PUBLIC LICENSE v3

namespace StudioFourteen.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Text;

[Generator(LanguageNames.CSharp)]
public class BindPropertyGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		SourceText attributeDefinition = SourceText.From($$"""
			// <auto-generated/>
			namespace StudioFourteen;
			[System.AttributeUsage(System.AttributeTargets.Property)]
			public class BindAttribute : System.Attribute
			{
			}
			""", Encoding.UTF8);

		context.RegisterPostInitializationOutput(ctx =>
		{
			ctx.AddSource($"StudioFourteen.BindAttribute.g.cs", attributeDefinition);
		});

		IncrementalValuesProvider<IPropertySymbol> pipeline = context.SyntaxProvider.ForAttributeWithMetadataName(
			"StudioFourteen.BindAttribute",
			(node, _) => true,
			(context, _) => (IPropertySymbol)context.TargetSymbol);

		context.RegisterSourceOutput(pipeline, this.Generate);
	}

	private void Generate(SourceProductionContext context, IPropertySymbol property)
	{
		string fileName = $"{property.ContainingType.Name}_{property.Name}.g.cs";

		string namespaceStr = property.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));
		string typeStr = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

		string classStr = property.ContainingType.Name;

		if (property.ContainingType.IsGenericType)
		{
			////property.ContainingType.OriginalDefinition
			classStr += "<T>";
		}

		string getMethod = string.Empty;
		if (property.GetMethod != null)
			getMethod = $"{property.GetMethod.DeclaredAccessibility.ToSource(Accessibility.Public)} get => _{property.Name};";

		string setMethod = string.Empty;
		if (property.SetMethod != null)
		{
			setMethod = $$"""
				{{property.SetMethod.DeclaredAccessibility.ToSource(Accessibility.Public)}} set
				{
					if (_{{property.Name}} == value)
						return;

					_{{property.Name}} = value;
					this.NotifyPropertyChanged("{{property.Name}}");
				}
				""";
		}

		SourceText source = SourceText.From($$"""
			// <auto-generated/>
			namespace {{namespaceStr}};
			partial class {{classStr}}
			{
				private {{typeStr}} _{{property.Name}};

				{{property.DeclaredAccessibility.ToSource(Accessibility.Internal)}} partial {{typeStr}} {{property.Name}}
				{
					{{getMethod}}
					{{setMethod}}
				}

				partial void On{{property.Name}}PropertyChanged({{typeStr}} oldValue, {{typeStr}} newValue);
			}
			""",
			Encoding.UTF8);

		context.AddSource(fileName, source);
	}
}

public static class AccessibilityExtensions
{
	public static string ToSource(this Accessibility self, Accessibility defaultAccessibility)
	{
		if (self == defaultAccessibility)
			return string.Empty;

		switch (self)
		{
			case Accessibility.Private: return "private";
			case Accessibility.Protected: return "protected";
			case Accessibility.Internal: return "internal";
			case Accessibility.Public: return "public";
		}

		return string.Empty;
	}
}
