// .                    @@             _____ _______ _    _ _____ _____ ____
//          @       @@@@@             / ____|__   __| |  | |  __ \_   _/ __ \
//         @@@  @@@@                 | (___    | |  | |  | | |  | || || |  | |
//         @@@@@@@@@  @    @          \___ \   | |  | |  | | |  | || || |  | |
//        @@@@       @@@@@@@          ____) |  | |  | |__| | |__| || || |__| |
//    @@@@@             @@@          |_____/   |_|   \____/|_____/_____\____/
//     @@@      @@@      @@        ___     _    _   _  __   _____  ___  ___  _  _
//      @@    @@@@@@@    @@       |  _|  / _ \ | | | || _ \|_   _|| __|| __|| \| |
//      @@    @@@@@@@    @   @    | __| | (_) || |_| ||   /  | |  | _| | _| | .` |
//    @@@@      @@@      @@@@     |_|    \___/  \___/ |_|_\  |_|  |___||___||_|\_|
//     @@@@             @@@        https://github.com/UnlostWorld/StudioFourteen
//       @@@@@      @@@@@
//        @@@@@@@@@@@@@@                This software is licensed under the
//            @@@@  @                  GNU AFFERO GENERAL PUBLIC LICENSE v3

namespace StudioFourteen.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Text;

[Generator(LanguageNames.CSharp)]
public class ServicesAccessGenerator : IIncrementalGenerator
{
	private static Dictionary<string, string> serviceTypes = new();

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		SourceText attributeDefinition = SourceText.From($$"""
			// <auto-generated/>
			namespace StudioFourteen;
			[System.AttributeUsage(System.AttributeTargets.Class)]
			public class ServicesAttribute : System.Attribute
			{
			}

			[System.AttributeUsage(System.AttributeTargets.Class)]
			public class ServiceAttribute : System.Attribute
			{
			}
			""", Encoding.UTF8);

		context.RegisterPostInitializationOutput(ctx =>
		{
			ctx.AddSource($"StudioFourteen.ServicesAttribute.g.cs", attributeDefinition);
		});

		IncrementalValuesProvider<ITypeSymbol> collectPipeline = context.SyntaxProvider.ForAttributeWithMetadataName(
			"StudioFourteen.ServiceAttribute",
			(node, _) => true,
			(context, _) => (ITypeSymbol)context.TargetSymbol);

		context.RegisterSourceOutput(collectPipeline, this.Collect);

		IncrementalValuesProvider<ITypeSymbol> pipeline = context.SyntaxProvider.ForAttributeWithMetadataName(
			"StudioFourteen.ServicesAttribute",
			(node, _) => true,
			(context, _) => (ITypeSymbol)context.TargetSymbol);

		context.RegisterSourceOutput(pipeline, this.Generate);
	}

	private void Collect(SourceProductionContext context, ITypeSymbol type)
	{
		serviceTypes[$"{type.ContainingNamespace.OriginalDefinition}.{type.Name}"] = type.Name;
	}

	private void Generate(SourceProductionContext context, ITypeSymbol type)
	{
		string fileName = $"{type.Name}.g.cs";

		string namespaceStr = type.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

		StringBuilder sb = new();

		sb.AppendLine($"// <auto-generated/>");
		sb.AppendLine($"namespace {namespaceStr};");
		sb.AppendLine($"using System.ComponentModel;");
		sb.AppendLine($"partial class {type.Name}");
		sb.AppendLine("{");

		foreach (KeyValuePair<string, string> keyVal in serviceTypes)
		{
			sb.AppendLine($"	protected static {keyVal.Key} {keyVal.Value} => ServiceManager.GetService<{keyVal.Key}>();");
		}

		sb.AppendLine("}");

		SourceText source = SourceText.From(sb.ToString(), Encoding.UTF8);

		context.AddSource(fileName, source);
	}
}