// .                    @@             _____ _______ _    _ _____ _____ ____
//          @       @@@@@             / ____|__   __| |  | |  __ \_   _/ __ \
//         @@@  @@@@                 | (___    | |  | |  | | |  | || || |  | |
//         @@@@@@@@@  @    @          \___ \   | |  | |  | | |  | || || |  | |
//        @@@@       @@@@@@@          ____) |  | |  | |__| | |__| || || |__| |
//    @@@@@             @@@          |_____/   |_|   \____/|_____/_____\____/
//     @@@      @@@      @@        ___     _    _   _  __   _____  ___  ___  _  _
//      @@    @@@@@@@    @@       |  _|  / _ \ | | | || _ \|_   _|| __|| __|| \| |
//      @@    @@@@@@@    @   @    | __| | (_) || |_| ||   /  | |  | _| | _| | .` |
//    @@@@      @@@      @@@@     |_|    \___/  \___/ |_|_\  |_|  |___||___||_|\_|
//     @@@@             @@@        https://github.com/UnlostWorld/StudioFourteen
//       @@@@@      @@@@@
//        @@@@@@@@@@@@@@                This software is licensed under the
//            @@@@  @                  GNU AFFERO GENERAL PUBLIC LICENSE v3

namespace StudioFourteen.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

[Generator(LanguageNames.CSharp)]
public class ServicesAccessGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		SourceText attributeDefinition = SourceText.From($$"""
			// <auto-generated/>
			namespace StudioFourteen;
			[System.AttributeUsage(System.AttributeTargets.Class)]
			public class ServicesAttribute : System.Attribute
			{
			}
			""", Encoding.UTF8);

		context.RegisterPostInitializationOutput(ctx =>
		{
			ctx.AddSource($"StudioFourteen.ServicesAttribute.g.cs", attributeDefinition);
		});

		IncrementalValuesProvider<ITypeSymbol> pipeline = context.SyntaxProvider.ForAttributeWithMetadataName(
			"StudioFourteen.ServicesAttribute",
			(node, _) => true,
			(context, _) => (ITypeSymbol)context.TargetSymbol);

		context.RegisterSourceOutput(pipeline, this.Generate);
	}

	private void Generate(SourceProductionContext context, ITypeSymbol type)
	{
		string fileName = $"{type.Name}.g.cs";

		string namespaceStr = type.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));

		SourceText source = SourceText.From($$"""
			// <auto-generated/>
			namespace {{namespaceStr}};
			using System.ComponentModel;
			partial class {{type.Name}}
			{
				protected ServiceManager Services => ServiceManager.Instance;
			}
			""",
			Encoding.UTF8);

		context.AddSource(fileName, source);
	}
}