<Project>
  <PropertyGroup>
    <AssemblyName>StudioFourteen</AssemblyName>
    <IntermediateOutputPath>obj\x64\Debug\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>C:\Projects\StudioFourteen\StudioFourteen\obj\</MSBuildProjectExtensionsPath>
    <_TargetAssemblyProjectName>StudioFourteen</_TargetAssemblyProjectName>
    <RootNamespace>StudioFourteen</RootNamespace>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AppendTargetFramework>False</AppendTargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>.\bin\</OutputPath>
    <DocumentationFile>.\obj\StudioFourteen.xml</DocumentationFile>
    <NoWarn>1701;1702;SA1503;CS1591;SA1401;SA1516;CS0067;IDE0027;IDE0025;SA1011;SA1134;NU1903;</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <TrimMode>CopyUsed</TrimMode>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishTrimmed>false</PublishTrimmed>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.0.*</AssemblyVersion>
    <DalamudLibPath>$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <PackageIcon>light-pride-textless.png</PackageIcon>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(CI)' == 'true' OR '$(IsCI)' == 'true'">
    <DalamudLibPath>$(DALAMUD_HOME)/</DalamudLibPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Lib\**" />
    <Compile Remove="publish\**" />
    <EmbeddedResource Remove="Lib\**" />
    <EmbeddedResource Remove="publish\**" />
    <None Remove="Lib\**" />
    <None Remove="publish\**" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data\Documents\**" />
    <EmbeddedResource Include="Cursors\**" />
    <EmbeddedResource Include="Rendering\Shaders\*.hlsl" />
    <EmbeddedResource Include="Rendering\Meshes\*.jsonc" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\StudioFourteen.Reshade\bin\StudioFourteen.Reshade.dll" Link="StudioFourteen.Reshade.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Apos.WintabDN" Version="0.0.1" />
    <PackageReference Include="Crayon" Version="2.0.69" />
    <PackageReference Include="DependencyPropertyGenerator" Version="1.5.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="DotNetProjects.SVGImage" Version="5.2.3" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="JsonSubTypes" Version="2.0.1" />
    <PackageReference Include="lz4net" Version="1.0.15.93" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.13.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3124.44" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PropertyChanged.SourceGenerator" Version="1.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.5" />
    <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="VirtualizingWrapPanel" Version="2.1.1" />
  </ItemGroup>
  <PropertyGroup>
    <DefineConstants>DALAMUD</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <None Update="StudioFourteen.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lib\WpfUtils\WpfUtils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\Accessibility.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\apos.wintabdn\0.0.1\lib\netstandard2.0\Apos.WintabDN.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\crayon\2.0.69\lib\netstandard2.0\Crayon.dll" />
    <ReferencePath Include="C:\Users\yukiw\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Dalamud.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\dotnetprojects.svgimage\5.2.3\lib\net8.0-windows7.0\DotNetProjects.SVGImage.dll" />
    <ReferencePath Include="C:\Users\yukiw\AppData\Roaming\XIVLauncher\addon\Hooks\dev\FFXIVClientStructs.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\fontawesome.sharp\6.6.0\lib\net8.0-windows7.0\FontAwesome.Sharp.dll" />
    <ReferencePath Include="C:\Users\yukiw\AppData\Roaming\XIVLauncher\addon\Hooks\dev\ImGui.NET.dll" />
    <ReferencePath Include="C:\Users\yukiw\AppData\Roaming\XIVLauncher\addon\Hooks\dev\ImGuiScene.dll" />
    <ReferencePath Include="C:\Users\yukiw\AppData\Roaming\XIVLauncher\addon\Hooks\dev\InteropGenerator.Runtime.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\jsonsubtypes\2.0.1\lib\netstandard2.0\JsonSubTypes.dll" />
    <ReferencePath Include="C:\Users\yukiw\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Lumina.dll" />
    <ReferencePath Include="C:\Users\yukiw\AppData\Roaming\XIVLauncher\addon\Hooks\dev\Lumina.Excel.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\lz4net\1.0.15.93\lib\netstandard1.0\LZ4.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\lz4net.unsafe.netcore\1.0.15.93\lib\netstandard1.0\LZ4pn.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\microsoft.codeanalysis.csharp\4.13.0\lib\net9.0\Microsoft.CodeAnalysis.CSharp.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\microsoft.codeanalysis.csharp.scripting\4.13.0\lib\net9.0\Microsoft.CodeAnalysis.CSharp.Scripting.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\microsoft.codeanalysis.common\4.13.0\lib\net9.0\Microsoft.CodeAnalysis.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\microsoft.codeanalysis.scripting.common\4.13.0\lib\net9.0\Microsoft.CodeAnalysis.Scripting.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\Microsoft.CSharp.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\Microsoft.VisualBasic.Core.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\Microsoft.VisualBasic.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\Microsoft.VisualBasic.Forms.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\microsoft.web.webview2\1.0.3124.44\lib_manual\netcoreapp3.0\Microsoft.Web.WebView2.Core.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\microsoft.web.webview2\1.0.3124.44\lib_manual\netcoreapp3.0\Microsoft.Web.WebView2.WinForms.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\microsoft.web.webview2\1.0.3124.44\lib_manual\net5.0-windows10.0.17763.0\Microsoft.Web.WebView2.Wpf.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\Microsoft.Win32.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\Microsoft.Win32.Registry.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\Microsoft.Win32.Registry.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\Microsoft.Win32.SystemEvents.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\mscorlib.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\netstandard.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\newtonsoft.json\13.0.1\lib\netstandard2.0\Newtonsoft.Json.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\PresentationCore.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\PresentationFramework.Aero.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\PresentationFramework.Aero2.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\PresentationFramework.AeroLite.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\PresentationFramework.Classic.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\PresentationFramework.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\PresentationFramework.Luna.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\PresentationFramework.Royale.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\PresentationUI.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\ReachFramework.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\serilog\4.0.0\lib\net8.0\Serilog.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\serilog.sinks.debug\3.0.0\lib\net8.0\Serilog.Sinks.Debug.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\sharpdx.d3dcompiler\4.2.0\lib\netstandard1.1\SharpDX.D3DCompiler.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\sharpdx.direct3d11\4.2.0\lib\netstandard1.1\SharpDX.Direct3D11.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\sharpdx.direct3d9\4.2.0\lib\netstandard1.3\SharpDX.Direct3D9.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\sharpdx\4.2.0\lib\netstandard1.1\SharpDX.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\sharpdx.dxgi\4.2.0\lib\netstandard1.1\SharpDX.DXGI.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\sixlabors.fonts\2.0.8\lib\net6.0\SixLabors.Fonts.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\sixlabors.imagesharp\3.1.7\lib\net6.0\SixLabors.ImageSharp.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\sixlabors.imagesharp.drawing\2.1.5\lib\net6.0\SixLabors.ImageSharp.Drawing.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.AppContext.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Buffers.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.CodeDom.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Collections.Concurrent.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Collections.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Collections.Immutable.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Collections.NonGeneric.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Collections.Specialized.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ComponentModel.Annotations.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ComponentModel.DataAnnotations.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ComponentModel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ComponentModel.EventBasedAsync.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ComponentModel.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ComponentModel.TypeConverter.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Configuration.ConfigurationManager.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Configuration.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Console.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Core.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Data.Common.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Data.DataSetExtensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Data.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Design.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.Contracts.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.Debug.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.DiagnosticSource.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.EventLog.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.FileVersionInfo.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.PerformanceCounter.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.Process.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.StackTrace.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.TextWriterTraceListener.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.Tools.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.TraceSource.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Diagnostics.Tracing.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.DirectoryServices.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Drawing.Common.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Drawing.Design.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Drawing.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Drawing.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Dynamic.Runtime.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Formats.Asn1.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Formats.Nrbf.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Formats.Tar.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Globalization.Calendars.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Globalization.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Globalization.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.Compression.Brotli.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.Compression.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.Compression.FileSystem.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.Compression.ZipFile.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.FileSystem.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.FileSystem.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.FileSystem.DriveInfo.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.FileSystem.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.FileSystem.Watcher.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.IsolatedStorage.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.MemoryMappedFiles.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.IO.Packaging.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.Pipelines.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.Pipes.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.Pipes.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.IO.UnmanagedMemoryStream.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Linq.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Linq.Expressions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Linq.Parallel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Linq.Queryable.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Memory.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.Http.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.Http.Json.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.HttpListener.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.Mail.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.NameResolution.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.NetworkInformation.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.Ping.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.Quic.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.Requests.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.Security.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.ServicePoint.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.Sockets.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.WebClient.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.WebHeaderCollection.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.WebProxy.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.WebSockets.Client.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Net.WebSockets.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Numerics.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Numerics.Vectors.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ObjectModel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Printing.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Private.Windows.Core.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Reflection.DispatchProxy.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Reflection.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Reflection.Emit.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Reflection.Emit.ILGeneration.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Reflection.Emit.Lightweight.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Reflection.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Reflection.Metadata.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Reflection.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Reflection.TypeExtensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Resources.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Resources.Reader.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Resources.ResourceManager.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Resources.Writer.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.CompilerServices.Unsafe.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.CompilerServices.VisualC.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Handles.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.InteropServices.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.InteropServices.JavaScript.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.InteropServices.RuntimeInformation.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Intrinsics.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Loader.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Numerics.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Serialization.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Serialization.Formatters.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Serialization.Json.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Serialization.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Runtime.Serialization.Xml.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Claims.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.Algorithms.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.Cng.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.Csp.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.Encoding.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.OpenSsl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.Pkcs.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.ProtectedData.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.X509Certificates.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Security.Cryptography.Xml.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Security.Permissions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Principal.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.Principal.Windows.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Security.SecureString.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ServiceModel.Web.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ServiceProcess.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Text.Encoding.CodePages.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Text.Encoding.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Text.Encoding.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Text.Encodings.Web.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Text.Json.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Text.RegularExpressions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Threading.AccessControl.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.Channels.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.Overlapped.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.Tasks.Dataflow.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.Tasks.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.Tasks.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.Tasks.Parallel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.Thread.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.ThreadPool.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Threading.Timer.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Transactions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Transactions.Local.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.ValueTuple.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Web.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Web.HttpUtility.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Windows.Controls.Ribbon.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Windows.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Windows.Extensions.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Windows.Forms.Design.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Windows.Forms.Design.Editors.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Windows.Forms.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Windows.Forms.Primitives.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Windows.Input.Manipulations.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Windows.Presentation.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\System.Xaml.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Xml.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Xml.Linq.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Xml.ReaderWriter.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Xml.Serialization.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Xml.XDocument.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Xml.XmlDocument.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Xml.XmlSerializer.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Xml.XPath.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\ref\net9.0\System.Xml.XPath.XDocument.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\UIAutomationClient.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\UIAutomationClientSideProviders.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\UIAutomationProvider.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\UIAutomationTypes.dll" />
    <ReferencePath Include="C:\Users\yukiw\.nuget\packages\virtualizingwrappanel\2.1.1\lib\net6.0-windows7.0\VirtualizingWrapPanel.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\WindowsBase.dll" />
    <ReferencePath Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\ref\net9.0\WindowsFormsIntegration.dll" />
    <ReferencePath Include="C:\Projects\StudioFourteen\Lib\WpfUtils\bin\x64\Debug\WpfUtils.dll" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\AIO\AioWindow.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Analytics\AnalyticsOptPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Analytics\ErrorReportPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Animation\AnimationPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Appearance\CharacterPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Cameras\CameraPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Controls\PathDisplay.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\DragAndDrop\DragObjectVisual.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Environment\EnvironmentPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\History\HistoryPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Launcher\LauncherWindow.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Launcher\ToolBarPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Library\LibraryWindow.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Library\Selector\LibrarySelectorStyles.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Marketplace\MarketplacePanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Panels\LongTaskWindow.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Panels\PanelWindowStyle.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Photos\CaptureAnimationWindow.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Photos\PhotoPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Posing\BlendInspector.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Posing\BlendTargetView.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Posing\Body\MatrixView.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Posing\ExpressionsView.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Posing\EyeInspector.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Posing\Hands\MatrixView.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Posing\PoseWindow.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Posing\TransformInspector.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Rendering\Gizmos\GizmoControlPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Reshade\NotSupportedPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Scripting\ScriptPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Settings\SettingsPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\Targets\TargetsPanel.g.cs" />
    <Compile Include="C:\Projects\StudioFourteen\StudioFourteen\obj\x64\Debug\GeneratedInternalTypeHelper.g.cs" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="C:\Program Files\dotnet\sdk\9.0.103\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll" />
    <Analyzer Include="C:\Program Files\dotnet\sdk\9.0.103\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\Microsoft.CodeAnalysis.NetAnalyzers.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\dependencypropertygenerator\1.5.0\analyzers\dotnet\roslyn4.3.1\cs\DependencyPropertyGenerator.Attributes.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\dependencypropertygenerator\1.5.0\analyzers\dotnet\roslyn4.3.1\cs\DependencyPropertyGenerator.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\dependencypropertygenerator\1.5.0\analyzers\dotnet\roslyn4.3.1\cs\H.Generators.Extensions.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\microsoft.codeanalysis.analyzers\3.11.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\microsoft.codeanalysis.analyzers\3.11.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\microsoft.windows.cswin32\0.3.183\analyzers\cs\MessagePack.Annotations.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\microsoft.windows.cswin32\0.3.183\analyzers\cs\MessagePack.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\microsoft.windows.cswin32\0.3.183\analyzers\cs\Microsoft.Bcl.AsyncInterfaces.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\microsoft.windows.cswin32\0.3.183\analyzers\cs\Microsoft.Windows.CsWin32.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\microsoft.windows.cswin32\0.3.183\analyzers\cs\Microsoft.Windows.SDK.Win32Docs.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\microsoft.windows.cswin32\0.3.183\analyzers\cs\System.Text.Encodings.Web.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\microsoft.windows.cswin32\0.3.183\analyzers\cs\System.Text.Json.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\propertychanged.sourcegenerator\1.1.1\analyzers\dotnet\cs\PropertyChanged.SourceGenerator.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\stylecop.analyzers.unstable\1.2.0.556\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll" />
    <Analyzer Include="C:\Users\yukiw\.nuget\packages\stylecop.analyzers.unstable\1.2.0.556\analyzers\dotnet\cs\StyleCop.Analyzers.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\analyzers/dotnet/cs/Microsoft.Interop.ComInterfaceGenerator.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\analyzers/dotnet/cs/Microsoft.Interop.LibraryImportGenerator.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\analyzers/dotnet/cs/Microsoft.Interop.SourceGeneration.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.2\analyzers/dotnet/cs/System.Text.RegularExpressions.Generator.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\analyzers/dotnet/System.Windows.Forms.Analyzers.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\analyzers/dotnet/cs/System.Windows.Forms.Analyzers.CSharp.dll" />
    <Analyzer Include="C:\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\9.0.2\analyzers/dotnet/cs/System.Windows.Forms.Analyzers.CodeFixes.CSharp.dll" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>