<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<AppendTargetFramework>False</AppendTargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<OutputPath>.\bin\</OutputPath>
		<DocumentationFile>.\obj\StudioFourteen.xml</DocumentationFile>
		<NoWarn>1701;1702;SA1503;CS1591;SA1401;SA1516;CS0067;IDE0027;IDE0025;SA1011;SA1134;</NoWarn>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Nullable>enable</Nullable>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<TrimMode>CopyUsed</TrimMode>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PublishTrimmed>false</PublishTrimmed>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<Deterministic>false</Deterministic>
		<AssemblyVersion>1.0.0.*</AssemblyVersion>
		<DalamudLibPath>$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
		<ApplicationIcon>Assets\icon.ico</ApplicationIcon>
		<PackageIcon>light-pride-textless.png</PackageIcon>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition="'$(CI)' == 'true' OR '$(IsCI)' == 'true'">
		<DalamudLibPath>$(DALAMUD_HOME)/</DalamudLibPath>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Lib\**" />
		<Compile Remove="publish\**" />
		<EmbeddedResource Remove="Lib\**" />
		<EmbeddedResource Remove="publish\**" />
		<None Remove="Lib\**" />
		<None Remove="publish\**" />
		<Page Remove="Lib\**" />
		<Page Remove="publish\**" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\*.*" />
		<Resource Include="Effects\bin\*.ps" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Data\Documents\*.*" />
	</ItemGroup>


	<ItemGroup>
	  <Content Include="Assets\icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(DalamudLibPath)\..\..\..\dalamud.boot.log" Link="dalamud.boot.log" />
		<None Include="$(DalamudLibPath)\..\..\..\dalamud.log" Link="dalamud.log" />
		<None Include="$(DalamudLibPath)\..\..\..\pluginConfigs\StudioFourteen.json" Link="config.json" />
		<None Include="..\Assets\Icon\light-pride-textless.png">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Apos.WintabDN" Version="0.0.1" />
		<PackageReference Include="DependencyPropertyGenerator" Version="1.4.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
		<PackageReference Include="PropertyChanged.SourceGenerator" Version="1.0.8">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.4" />
		<PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="TerraFX.Interop.Windows" Version="10.0.26100" />
		<PackageReference Include="VirtualizingWrapPanel" Version="2.0.12" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="FFXIVClientStructs">
			<HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>$(DalamudLibPath)Newtonsoft.Json.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Dalamud">
			<HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="ImGui.NET">
			<HintPath>$(DalamudLibPath)ImGui.NET.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="ImGuiScene">
			<HintPath>$(DalamudLibPath)ImGuiScene.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Lumina">
			<HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Lumina.Excel">
			<HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Update="StudioFourteen.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Page Include="Properties\DesignTimeResources.xaml" Condition="'$(DesignTime)'=='true'">
			<Generator>MSBuild:Compile</Generator>
			<SubType>Designer</SubType>
			<ContainsDesignTimeResources>true</ContainsDesignTimeResources>
		</Page>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Lib\WpfUtils\WpfUtils.csproj" />
	</ItemGroup>

	<Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
		<!-- Work around https://github.com/dotnet/wpf/issues/6792 -->

		<ItemGroup>
			<FilteredAnalyzer Include="@(Analyzer-&gt;Distinct())" />
			<Analyzer Remove="@(Analyzer)" />
			<Analyzer Include="@(FilteredAnalyzer)" />
		</ItemGroup>
	</Target>

	<Target Name="EffectCompile" BeforeTargets="CoreCompile">
		<Exec Command="&quot;$(MSBuildProgramFiles32)\Windows Kits\10\bin\10.0.26100.0\x64\fxc.exe&quot; /T ps_3_0 /Fo Effects/bin/WindowMask.ps Effects/WindowMask.fx" />
	</Target>

</Project>
