<Project Sdk="Dalamud.NET.SDK/13.0.0">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<AppendTargetFramework>False</AppendTargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<OutputPath>.\bin\</OutputPath>
		<DocumentationFile>.\obj\StudioFourteen.xml</DocumentationFile>
		<NoWarn>1701;1702;SA1503;CS1591;SA1401;SA1516;CS0067;IDE0027;IDE0025;SA1011;SA1134;NU1903;</NoWarn>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Nullable>enable</Nullable>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<TrimMode>CopyUsed</TrimMode>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PublishTrimmed>false</PublishTrimmed>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AssemblyVersion>2.0.0.0</AssemblyVersion>
		<Platforms>x64</Platforms>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Content\**" />
		<Content Include="Content\**" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<ItemGroup>
		<None Update="StudioFourteen.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Apos.WintabDN" Version="0.0.1" />
		<PackageReference Include="Crayon" Version="2.0.69" />
		<PackageReference Include="lz4net" Version="1.0.15.93" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.14.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SharpDX" Version="4.2.0" />
		<PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
		<PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
		<PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
		<PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
		<PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Avalonia" Version="11.3.12" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
		<PackageReference Include="Avalonia.Themes.Simple" Version="11.3.12" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
		<PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.3.12" />
		<PackageReference Include="Svg.Controls.Avalonia" Version="11.3.9.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="PropertyGenerator.Avalonia" Version="1.2.6" />


		<!--Condition
		below is needed to remove Avalonia.Diagnostics package from build output in Release
		configuration.-->
		<PackageReference Include="Avalonia.Diagnostics" Version="11.3.9">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
	</ItemGroup>

</Project>